### ISSUE TITLE
Doubles are parsed as object-attributes pairs

### ISSUE THREAD

**Issue by asikstel** [mmontone/burgled-batteries.syntax#1]
Hello,

I'm runnning sbcl, newest version, burgled-batteries.syntax from quciklisp.
If i try to pass a double to some function b-b.syntax thinks it's a call to objects attribute.

'[numpy.sin(1.5d0)](BURGLED-BATTERIES.SYNTAX::CALL* %28BURGLED-BATTERIES.SYNTAX::REF*) "sin"
                                 (PYTHON.CFFI:OBJECT.GET-ATTR*
                                  (PYTHON.CFFI:NUMBER.INT\* 1) "5d0"))

maybe I mistake, but still it would be a cool feature if would just work like this.

Best regargs,
Aleksey

**Comment by mmontone** [comment]
Ok. I'm looking at that. Note that 1.5d0 is not valid Python syntax: https://docs.python.org/2/reference/lexical_analysis.html. I think you are trying to use Lisp syntax there.

So, you can work around it with something like:

(let (($my-num 1.5d0))
     [numpy.sin($my-num)])

Anyway, I'm implementing Python literal float syntax now.

**Comment by mmontone** [comment]
I've implemented Python float syntax.

You can try things like these now:

BURGLED-BATTERIES> [^numpy.sin(1.5)]
0.9974949866040544d0
BURGLED-BATTERIES> [^numpy.sin(1.5e2)]
-0.7148764296291646d0
BURGLED-BATTERIES> [^numpy.sin(-1.5e2)]
0.7148764296291646d0
BURGLED-BATTERIES> [^numpy.sin(-1.5-e3)]
; Evaluation aborted on Incomplete parse..
BURGLED-BATTERIES> [^numpy.sin(-1.5e-3)]
-0.0014999994505385647d0

Please test.

**Comment by asikstel** [comment]
That was amazingly fast! 
Thanks a lot, works perfectly!
