### ISSUE TITLE
Arguments are reverted in calls to python function

### ISSUE THREAD

**Issue by asikstel** [mmontone/burgled-batteries.syntax#2]
Hello, me again.
I've found that arguments in calls to python functions are getting reverted somehow.
If I call the plot function of matplotlib.pyplot like this

(let\* (($x (list 1.0d0 2.0d0 3.0d0 4.0d0)) ($y (map 'list #'(lambda (x) (\* x x)) $x)))
       (let (($plt [matplotlib.pyplot]))
         (progn
           [$plt.plot($x, $y, "-" , linewidth=5)]
           [matplotlib.pyplot.show()])))

then plot is called as plot( '-', y, x, **kwargs) as you can see in the quoted output:

(LET\* (($X (LIST 1.0d0 2.0d0 3.0d0 4.0d0))
       ($Y (MAP 'LIST #'(LAMBDA (X) (\* X X)) $X)))
  (LET (($PLT
         (PYTHON.CFFI:OBJECT.GET-ATTR*
          (BURGLED-BATTERIES.SYNTAX::REF\* "matplotlib") "pyplot")))
    (PROGN
     (LET ((#:KWARGS1550 (MAKE-HASH-TABLE)))
       (SETF (GETHASH "linewidth" #:KWARGS1550) (PYTHON.CFFI:NUMBER.INT\* 5))
       (BURGLED-BATTERIES::WITH-CPYTHON-POINTER (#:PYFUN1551
                                                 (PYTHON.CFFI:OBJECT.GET-ATTR-STRING*
                                                  $PLT "plot"))
         (PYTHON.CFFI:OBJECT.CALL\* #:PYFUN1551
                                   (LIST (PYTHON.CFFI:STRING.FROM-STRING\* "-")
                                         $Y $X)
                                   #:KWARGS1550)))
     (BURGLED-BATTERIES.SYNTAX::CALL*
      (PYTHON.CFFI:OBJECT.GET-ATTR*
       (BURGLED-BATTERIES.SYNTAX::REF\* "matplotlib") "pyplot")
      "show"))))

On the other hand

(let\* (($x (list 1.0d0 2.0d0 3.0d0 4.0d0)) ($y (map 'list #'(lambda (x) (\* x x)) $x)))
       (let (($plt [matplotlib.pyplot]))
         (progn
           [$plt.plot("-" , $x, $y, linewidth=5)]
           [matplotlib.pyplot.show()])))

works perfectly fine.

Also I'd like to make a suggestion. It would be really nice to be able to define an *args list and a **kwarags hashtable and pass it to some python function, e.g. like this

(let\* (($x (list 1.0d0 2.0d0 3.0d0 4.0d0)) ($y (map 'list #'(lambda (x) (\* x x)) $x)))
       (let (($plt [matplotlib.pyplot])
                  ($args (list $x $y "-"))
                  ($kwargs _some-lisp-hashtable-with-arguments_)
         (progn
           [$plt.plot(*$args, **$kwargs)]
           [matplotlib.pyplot.show()])))

Many thanks for your software and in advance for yout help. 

(N.B. I am trying solving numerical problems( FEM, finite volumes etc with lisp and C and do want to plot the solutions and other stuff. Unfortunately, the only plotting librarary  suitable for pulbications ( ps-output, nice looking, many features) is matplotlib which is written in python. Therefore, very very nice to have your packages!!)

**Comment by mmontone** [comment]
Thanks for the report! The reversed argument problem should not be hard to fix. I will look at it soon.

As for the _args and *_kwargs list, I will look at that later.

**Comment by mmontone** [comment]
I've fixed the arguments order issue. Please test.

**Comment by mmontone** [comment]
I've pushed a experimental patch for your second request (args, and kwargs).

You have to use kwargs with property lists, like this:

(run "import matplotlib.pyplot as plt")

(let\* (($x (list 1.0d0 2.0d0 3.0d0 4.0d0)) ($y (map 'list #'(lambda (x) (\* x x)) $x))
             ($args (list $x $y "-"))
($kwargs (list :linewidth 5)))
(progn
[plt.plot(_$args, *_$kwargs)]
[plt.show()]))

Although I'm afraid the parameters handling is not very clever atm, and this patch affects simple function calls (which don't use args/kwargs). So I may have to cook it a bit more.

I've pushed the patch nonetheless.

Please test!

**Comment by asikstel** [comment]
Both work perfectly fine, thanks for the fast replies!
(note that github.com removed the asterisks in your last code example since they're stupidly used for markdown)
Best regards
